language: node_js
node_js:
- '5'
deploy:
  skip_cleanup: true
  provider: npm
  email: berezin.mvdev@yahoo.com
  api_key:
    secure: IIIzkkfGzn+tk086TRwFFBnjyGOki75lqAN3vHe/Swvd2qj5Hxc2w1lySJCCEfHON0APLAgTANPxmffusgxiR0v6kmu1oqjcm9qktHSQPw9Du2cawtyB0+V20ggUr6a5wQnRW7gaMK1r5JGIMW2AzMAhpHdKEST7Mcr3QqoqXGv6369+mRY/mJrJRsr2NNRO511b1riqtuHv2loxf6ep9d8sc9B5p5PwaRGPcBXJhq6LBKBpCkFQG7Vy+GmiJz3kZ/jZbaZoTvKZZT1MwWMUKBH38Iz69EAG8uw04pfXVRpRwNlzoui0bLcljivEPqIteYS1FfMGWbzDHUtAo4Vn4VGu7T1oaYfxBHvNqOPrBAZW5tQKX1HLA29/ySutRqM8X/8jb64WKAYOBUhbaqVzYJiSYooHlGIrPmFeaH9Zwl/pPqin3yrawOULdPT+u48+tOBc5tHHVX8sv4M8GmmKvGER49U7HTKT0L900PB6AfjHbcy5cgdNaQjqv5tdm4MC8BA+CzexE21wF9FtG2FV8xe25oiLjprfVr8+Jyp56Te0X394tIVabDauoPKlR+/vPk58nOQ5unVbfiiHymHDQsfZplO9CFPeXUpfRbEGlp+EJfySDVRKAp9K67QDNUd92STWvSdUlIU6Pcvzu/toezhJJk9A+DBYNM43vxM6ls0=
